/* ══════════════════════════════════════════════════════════════════════════
   MUSCU RPG — lang.js
   Internationalisation (i18n) — Support 5 langues
   ══════════════════════════════════════════════════════════════════════════ */

var I18N = {
  fr: {
    lvl: 'Niveau',
    tab_seances: 'Séances',
    tab_pr: 'PR Big 6',
    tab_rpg: 'RPG',
    tab_simu: 'Simu',
    tab_stats: 'Stats',
    tab_badges: 'Badges',
    stitle_new_serie: 'Nouvelle série',
    label_date: 'Date',
    label_type: 'Type de séance',
    label_ex: 'Exercice',
    label_ser: 'Séries',
    label_rep: 'Répétitions',
    label_pds: 'Poids (kg)',
    btn_save: 'Enregistrer',
    label_timer: 'Chrono de repos',
    timer_start: 'Démarrer',
    timer_stop: 'Arrêter',
    timer_reset: 'Reset',
    stitle_journal: 'Journal',
    filter_all: 'Tout',
    filter_ex: 'Exercice',
    filter_type: 'Type séance',
    filter_date: 'Date',
    filter_all_types: '-- Tous les types --',
    filter_all_dates: '-- Toutes les dates --',
    stitle_pr: 'PR — Big 6',
    stitle_rpg: 'Progression RPG',
    label_score_global: 'Score Global',
    stitle_programs: 'Mes Programmes',
    btn_new: 'Nouveau',
    placeholder_prog_name: 'Nom du programme...',
    btn_save_prog: 'Sauver',
    label_prog_type: 'Type de séance (appliqué au log)',
    label_add_ex: 'Ajouter un exercice',
    btn_add_list: 'Ajouter à la liste',
    stitle_content_block: 'Contenu du bloc',
    stitle_gains: 'Prévisions de Gain',
    label_gain_global: 'Gain Global Estimé',
    btn_confirm_session: 'Confirmer la séance (Log)',
    btn_back: 'Retour aux programmes',
    stitle_stats: 'Statistiques',
    btn_export: 'Exporter',
    btn_import: 'Importer',
    label_vol_total: 'Volume total',
    label_sessions: 'Séances',
    label_pr_done: 'PR réalisés',
    label_ex_diff: 'Exercices diff.',
    label_ex_analyze: 'Exercice à analyser',
    label_chart_vol: 'Volume par séance',
    label_chart_pr: 'Évolution 1RM estimé',
    label_chart_empty: 'Sélectionne un exercice pour voir son évolution',
    stitle_badges: 'Badges & Progression',
    label_muscles: 'Groupes Musculaires',
    menu_home: 'RPG (Accueil)',
    menu_profil: 'Profil',
    menu_settings: 'Paramètres',
    label_prenom: 'Prénom',
    label_nom: 'Nom',
    label_age: 'Âge',
    label_poids: 'Poids (kg)',
    label_taille: 'Taille (cm)',
    btn_save_profile: 'Enregistrer le Profil',
    label_lang: 'Langue',
    label_theme: 'Thème Visuel',
    theme_dark: 'SOMBRE',
    theme_light: 'CLAIR',
    theme_amber: 'AMBRE',
    lvl_avg: 'Niveau moyen : ',
    lvl_keep_training: "Continue à t'entraîner !",
    accumulated: 'accumulé',
    hypertrophy: 'Hypertrophie',
    strength: 'Force',
    hyperstrength: 'Hyperforce (PR)',
    endurance: 'Endurance musculaire',
    deload: 'Décharge',
    pecs: 'Pectoraux',
    back: 'Dorsaux',
    shoulders: 'Épaules',
    biceps: 'Biceps',
    triceps: 'Triceps',
    quads: 'Quadriceps',
    hams: 'Ischios',
    glutes: 'Fessiers',
    calves: 'Mollets',
    abs: 'Abdos',
    lumbars: 'Lombaires',
    traps: 'Trapèzes',
    fullbody: 'Full body',
    sets: 'séries',
    no_sets: 'Aucune série.<br>Saisis ta première entrée !',
    no_sets_filter: 'Aucune série pour ce filtre.',
    no_data: 'Aucune donnée',
    pr_on: 'du',
    edit: 'Éditer',
    empty_list: 'Liste vide.',
    global_level: 'Niveau Global',
    level_up_global: 'MONTÉE DE NIVEAU GLOBALE !',
    xp_left_for: 'Encore {{xp}} XP pour le niveau {{lvl}}',
    xp_missing: 'Manque {{xp}} XP',
    all: 'Tous',
    exercises: 'Exercices',
    achievements: 'Succès',
    special: 'Spéciaux',
    career_stats: 'Statistiques de Carrière',
    records: 'Records',
    unlocked_by: 'Débloqué par seulement {{rate}} des athlètes',
    special_achievements: 'Hauts Faits Spéciaux',
    progress: 'Progression',
    sessions: 'séances',
    diff_exercises: 'exercices',
    choose_ex: 'Choisir un exercice',
    est_hybrid_1rm: '1RM estimé Hybride',
    p_7d: '7 derniers jours',
    p_30d: '30 derniers jours',
    p_90d: '90 derniers jours',
    p_1y: '1 an',
    p_all: 'Tout',
    profile_saved: 'Profil enregistré !',
    lang_updated_to: 'Langue mise à jour',
    new_program: 'Nouveau Programme',
    untitled: 'Sans nom',
    confirm_delete: 'Supprimer ?',
    confirm_session: 'Confirmer la séance ?',
    no_programs: 'Aucun programme.'
  },
  en: {
    lvl: 'Level',
    tab_seances: 'Logs',
    tab_pr: 'PR Big 6',
    tab_rpg: 'RPG',
    tab_simu: 'Simu',
    tab_stats: 'Stats',
    tab_badges: 'Badges',
    stitle_new_serie: 'New Set',
    label_date: 'Date',
    label_type: 'Session Type',
    label_ex: 'Exercise',
    label_ser: 'Sets',
    label_rep: 'Reps',
    label_pds: 'Weight (kg)',
    btn_save: 'Save',
    label_timer: 'Rest Timer',
    timer_start: 'Start',
    timer_stop: 'Stop',
    timer_reset: 'Reset',
    stitle_journal: 'Journal',
    filter_all: 'All',
    filter_ex: 'Exercise',
    filter_type: 'Type',
    filter_date: 'Date',
    filter_all_types: '-- All types --',
    filter_all_dates: '-- All dates --',
    stitle_pr: 'PR — Big 6',
    stitle_rpg: 'RPG Progression',
    label_score_global: 'Global Score',
    stitle_programs: 'My Programs',
    btn_new: 'New',
    placeholder_prog_name: 'Program name...',
    btn_save_prog: 'Save',
    label_prog_type: 'Session Type (for log)',
    label_add_ex: 'Add Exercise',
    btn_add_list: 'Add to List',
    stitle_content_block: 'Block Content',
    stitle_gains: 'Gain Forecast',
    label_gain_global: 'Est. Global Gain',
    btn_confirm_session: 'Confirm Session (Log)',
    btn_back: 'Back to Programs',
    stitle_stats: 'Statistics',
    btn_export: 'Export',
    btn_import: 'Import',
    label_vol_total: 'Total Volume',
    label_sessions: 'Sessions',
    label_pr_done: 'PRs achieved',
    label_ex_diff: 'Diff. Exercises',
    label_ex_analyze: 'Analyze Exercise',
    label_chart_vol: 'Volume per session',
    label_chart_pr: 'Estimated 1RM trend',
    label_chart_empty: 'Select an exercise to see progress',
    stitle_badges: 'Badges & Progress',
    label_muscles: 'Muscle Groups',
    menu_home: 'RPG (Home)',
    menu_profil: 'Profile',
    menu_settings: 'Settings',
    label_prenom: 'First Name',
    label_nom: 'Last Name',
    label_age: 'Age',
    label_poids: 'Weight (kg)',
    label_taille: 'Height (cm)',
    btn_save_profile: 'Save Profile',
    label_lang: 'Language',
    label_theme: 'Visual Theme',
    theme_dark: 'DARK',
    theme_light: 'LIGHT',
    theme_amber: 'AMBER',
    lvl_avg: 'Avg Level: ',
    lvl_keep_training: 'Keep training!',
    accumulated: 'accumulated',
    hypertrophy: 'Hypertrophy',
    strength: 'Strength',
    hyperstrength: 'Hyperstrength (PR)',
    endurance: 'Muscular Endurance',
    deload: 'Deload',
    pecs: 'Chest',
    back: 'Back',
    shoulders: 'Shoulders',
    biceps: 'Biceps',
    triceps: 'Triceps',
    quads: 'Quads',
    hams: 'Hamstrings',
    glutes: 'Glutes',
    calves: 'Calves',
    abs: 'Abs',
    lumbars: 'Lower Back',
    traps: 'Traps',
    fullbody: 'Full Body',
    sets: 'sets',
    no_sets: 'No sets.<br>Record your first one!',
    no_sets_filter: 'No sets for this filter.',
    no_data: 'No data',
    pr_on: 'on',
    edit: 'Edit',
    empty_list: 'Empty list.',
    global_level: 'Global Level',
    level_up_global: 'GLOBAL LEVEL UP!',
    xp_left_for: '{{xp}} XP left for level {{lvl}}',
    xp_missing: '{{xp}} XP missing',
    all: 'All',
    exercises: 'Exercises',
    achievements: 'Achievements',
    special: 'Special',
    career_stats: 'Career Statistics',
    records: 'Records',
    unlocked_by: 'Unlocked by only {{rate}} of athletes',
    special_achievements: 'Special Achievements',
    progress: 'Progress',
    sessions: 'sessions',
    diff_exercises: 'exercises',
    choose_ex: 'Choose an exercise',
    est_hybrid_1rm: 'Est. Hybrid 1RM',
    p_7d: 'Last 7 days',
    p_30d: 'Last 30 days',
    p_90d: 'Last 90 days',
    p_1y: '1 year',
    p_all: 'All',
    profile_saved: 'Profile saved!',
    lang_updated_to: 'Language updated',
    xp_left_for: '{{xp}} XP left for level {{lvl}}',
    xp_missing: '{{xp}} XP missing',
    new_program: 'New Program',
    untitled: 'Untitled',
    confirm_delete: 'Delete?',
    confirm_session: 'Confirm session?',
    no_programs: 'No programs.'
  },
  de: {
    lvl: 'Level',
    tab_seances: 'Training',
    tab_pr: 'PR Big 6',
    tab_rpg: 'RPG',
    tab_simu: 'Simu',
    tab_stats: 'Statistik',
    tab_badges: 'Abzeichen',
    stitle_new_serie: 'Neuer Satz',
    label_date: 'Datum',
    label_type: 'Trainingstyp',
    label_ex: 'Übung',
    label_ser: 'Sätze',
    label_rep: 'Wdh.',
    label_pds: 'Gewicht (kg)',
    btn_save: 'Speichern',
    label_timer: 'Pause',
    timer_start: 'Start',
    timer_stop: 'Stopp',
    timer_reset: 'Reset',
    stitle_journal: 'Journal',
    filter_all: 'Alle',
    filter_ex: 'Übung',
    filter_type: 'Typ',
    filter_date: 'Datum',
    filter_all_types: '-- Alle Typen --',
    filter_all_dates: '-- Alle Daten --',
    stitle_pr: 'PR — Big 6',
    stitle_rpg: 'RPG Fortschritt',
    label_score_global: 'Gesamtpunktzahl',
    stitle_programs: 'Meine Programme',
    btn_new: 'Neu',
    placeholder_prog_name: 'Programmname...',
    btn_save_prog: 'Speichern',
    label_prog_type: 'Trainingstyp (für Log)',
    label_add_ex: 'Übung hinzufügen',
    btn_add_list: 'Zur Liste hinzufügen',
    stitle_content_block: 'Inhalt',
    stitle_gains: 'Gewinnprognose',
    label_gain_global: 'Gesch. Gesamtgewinn',
    btn_confirm_session: 'Sitzung bestätigen',
    btn_back: 'Zurück zu Programmen',
    stitle_stats: 'Statistiken',
    btn_export: 'Exportieren',
    btn_import: 'Importieren',
    label_vol_total: 'Gesamtvolumen',
    label_sessions: 'Sitzungen',
    label_pr_done: 'PRs erreicht',
    label_ex_diff: 'Diff. Übungen',
    label_ex_analyze: 'Übung analysieren',
    label_chart_vol: 'Volumen pro Sitzung',
    label_chart_pr: 'Trend gesch. 1RM',
    label_chart_empty: 'Wähle eine Übung aus',
    stitle_badges: 'Abzeichen & Fortschritt',
    label_muscles: 'Muskelgruppen',
    menu_home: 'RPG (Home)',
    menu_profil: 'Profil',
    menu_settings: 'Einstellungen',
    label_prenom: 'Vorname',
    label_nom: 'Nachname',
    label_age: 'Alter',
    label_poids: 'Gewicht (kg)',
    label_taille: 'Größe (cm)',
    btn_save_profile: 'Profil speichern',
    label_lang: 'Sprache',
    label_theme: 'Design',
    theme_dark: 'DUNKEL',
    theme_light: 'HELL',
    theme_amber: 'BERNSTEIN',
    lvl_avg: 'Durchschn. Level: ',
    lvl_keep_training: 'Trainiere weiter!',
    accumulated: 'gesammelt',
    hypertrophy: 'Hypertrophie',
    strength: 'Kraft',
    hyperstrength: 'Maximalkraft (PR)',
    endurance: 'Kraftausdauer',
    deload: 'Entlastung',
    pecs: 'Brust',
    back: 'Rücken',
    shoulders: 'Schultern',
    biceps: 'Bizeps',
    triceps: 'Trizeps',
    quads: 'Quads',
    hams: 'Beinbeuger',
    glutes: 'Gesäß',
    calves: 'Waden',
    abs: 'Bauchmuskeln',
    lumbars: 'Unterer Rücken',
    traps: 'Nacken',
    fullbody: 'Ganzkörper',
    sets: 'Sätze',
    no_sets: 'Keine Sätze.<br>Erfasse deine erste Trainingseinheit!',
    no_sets_filter: 'Keine Sätze für diesen Filter.',
    no_data: 'Keine Daten',
    pr_on: 'am',
    edit: 'Bearbeiten',
    empty_list: 'Liste leer.',
    global_level: 'Gesamtlevel',
    level_up_global: 'GESAMTLEVEL GESTIEGEN!',
    xp_left_for: 'Noch {{xp}} XP bis Level {{lvl}}',
    xp_missing: '{{xp}} XP fehlen',
    all: 'Alle',
    exercises: 'Übungen',
    achievements: 'Erfolge',
    special: 'Spezial',
    career_stats: 'Karrierestatistik',
    records: 'Rekorde',
    unlocked_by: 'Von nur {{rate}} der Athleten freigeschaltet',
    special_achievements: 'Spezielle Erfolge',
    progress: 'Fortschritt',
    sessions: 'Sitzungen',
    diff_exercises: 'Übungen',
    choose_ex: 'Wähle eine Übung',
    est_hybrid_1rm: 'Gesch. Hybrid 1RM',
    p_7d: 'Letzte 7 Tage',
    p_30d: 'Letzte 30 Tage',
    p_90d: 'Letzte 90 Tage',
    p_1y: '1 Jahr',
    p_all: 'Alle',
    profile_saved: 'Profil gespeichert!',
    lang_updated_to: 'Sprache aktualisiert',
    xp_left_for: 'Noch {{xp}} XP bis Level {{lvl}}',
    xp_missing: '{{xp}} XP fehlen',
    new_program: 'Neues Programm',
    untitled: 'Ohne Titel',
    confirm_delete: 'Löschen?',
    confirm_session: 'Sitzung bestätigen?',
    no_programs: 'Keine Programme.'
  },
  es: {
    lvl: 'Nivel',
    tab_seances: 'Sesiones',
    tab_pr: 'PR Big 6',
    tab_rpg: 'RPG',
    tab_simu: 'Simu',
    tab_stats: 'Estadísticas',
    tab_badges: 'Insignias',
    stitle_new_serie: 'Nueva serie',
    label_date: 'Fecha',
    label_type: 'Tipo de sesión',
    label_ex: 'Ejercicio',
    label_ser: 'Series',
    label_rep: 'Repeticiones',
    label_pds: 'Peso (kg)',
    btn_save: 'Guardar',
    label_timer: 'Temporizador',
    timer_start: 'Iniciar',
    timer_stop: 'Parar',
    timer_reset: 'Reiniciar',
    stitle_journal: 'Diario',
    filter_all: 'Todo',
    filter_ex: 'Ejercicio',
    filter_type: 'Tipo',
    filter_date: 'Fecha',
    filter_all_types: '-- Todos los tipos --',
    filter_all_dates: '-- Todas las fechas --',
    stitle_pr: 'PR — Big 6',
    stitle_rpg: 'Progresión RPG',
    label_score_global: 'Puntuación Global',
    stitle_programs: 'Mis Programas',
    btn_new: 'Nuevo',
    placeholder_prog_name: 'Nombre del programa...',
    btn_save_prog: 'Guardar',
    label_prog_type: 'Tipo de sesión (para log)',
    label_add_ex: 'Añadir Ejercicio',
    btn_add_list: 'Añadir a la lista',
    stitle_content_block: 'Contenido',
    stitle_gains: 'Previsión de Ganancia',
    label_gain_global: 'Ganancia Global Est.',
    btn_confirm_session: 'Confirmar sesión',
    btn_back: 'Volver a programas',
    stitle_stats: 'Estadísticas',
    btn_export: 'Exportar',
    btn_import: 'Importar',
    label_vol_total: 'Volumen total',
    label_sessions: 'Sesiones',
    label_pr_done: 'PRs logrados',
    label_ex_diff: 'Ejercicios diff.',
    label_ex_analyze: 'Analizar ejercicio',
    label_chart_vol: 'Volumen por sesión',
    label_chart_pr: 'Tendencia 1RM est.',
    label_chart_empty: 'Selecciona un ejercicio',
    stitle_badges: 'Insignias y Progreso',
    label_muscles: 'Grupos Musculares',
    menu_home: 'RPG (Inicio)',
    menu_profil: 'Perfil',
    menu_settings: 'Ajustes',
    label_prenom: 'Nombre',
    label_nom: 'Apellido',
    label_age: 'Edad',
    label_poids: 'Peso (kg)',
    label_taille: 'Altura (cm)',
    btn_save_profile: 'Guardar Perfil',
    label_lang: 'Idioma',
    label_theme: 'Tema Visual',
    theme_dark: 'OSCURO',
    theme_light: 'CLARO',
    theme_amber: 'ÁMBAR',
    lvl_avg: 'Nivel medio: ',
    lvl_keep_training: '¡Sigue entrenando!',
    accumulated: 'acumulado',
    hypertrophy: 'Hipertrofia',
    strength: 'Fuerza',
    hyperstrength: 'Hiperfuerza (PR)',
    endurance: 'Resistencia muscular',
    deload: 'Descarga',
    pecs: 'Pectorales',
    back: 'Espalda',
    shoulders: 'Hombros',
    biceps: 'Bíceps',
    triceps: 'Tríceps',
    quads: 'Cuádriceps',
    hams: 'Isquios',
    glutes: 'Glúteos',
    calves: 'Gemelos',
    abs: 'Abdominales',
    lumbars: 'Lumbares',
    traps: 'Trapecios',
    fullbody: 'Cuerpo completo',
    sets: 'series',
    no_sets: 'Sin series.<br>¡Registra tu primer entrenamiento!',
    no_sets_filter: 'Sin series para este filtro.',
    no_data: 'Sin datos',
    pr_on: 'el',
    edit: 'Editar',
    empty_list: 'Lista vacía.',
    global_level: 'Nivel Global',
    level_up_global: '¡NIVEL GLOBAL AUMENTADO!',
    xp_left_for: 'Faltan {{xp}} XP para el nivel {{lvl}}',
    xp_missing: 'Faltan {{xp}} XP',
    all: 'Todo',
    exercises: 'Ejercicios',
    achievements: 'Logros',
    special: 'Especial',
    career_stats: 'Estadísticas de Carrera',
    records: 'Récords',
    unlocked_by: 'Desbloqueado por solo el {{rate}} de los atletas',
    special_achievements: 'Logros Especiales',
    progress: 'Progreso',
    sessions: 'sesiones',
    diff_exercises: 'ejercicios',
    choose_ex: 'Elige un ejercicio',
    est_hybrid_1rm: '1RM est. Híbrido',
    p_7d: 'Últimos 7 días',
    p_30d: 'Últimos 30 días',
    p_90d: 'Últimos 90 días',
    p_1y: '1 año',
    p_all: 'Todo',
    profile_saved: '¡Perfil guardado!',
    lang_updated_to: 'Idioma actualizado',
    xp_left_for: 'Faltan {{xp}} XP para el nivel {{lvl}}',
    xp_missing: 'Faltan {{xp}} XP',
    new_program: 'Nuevo Programa',
    untitled: 'Sin título',
    confirm_delete: '¿Eliminar?',
    confirm_session: '¿Confirmar sesión?',
    no_programs: 'Sin programas.'
  },
  ja: {
    lvl: 'レベル',
    tab_seances: '記録',
    tab_pr: 'PR Big 6',
    tab_rpg: 'RPG',
    tab_simu: 'シミュ',
    tab_stats: '統計',
    tab_badges: 'バッジ',
    stitle_new_serie: '新しいセット',
    label_date: '日付',
    label_type: 'セッションタイプ',
    label_ex: '種目',
    label_ser: 'セット数',
    label_rep: 'レップ数',
    label_pds: '重量 (kg)',
    btn_save: '保存',
    label_timer: '休憩タイマー',
    timer_start: 'スタート',
    timer_stop: 'ストップ',
    timer_reset: 'リセット',
    stitle_journal: 'ジャーナル',
    filter_all: 'すべて',
    filter_ex: '種目',
    filter_type: 'タイプ',
    filter_date: '日付',
    filter_all_types: '-- すべてのタイプ --',
    filter_all_dates: '-- すべての日付 --',
    stitle_pr: 'PR — Big 6',
    stitle_rpg: 'RPG 進行状況',
    label_score_global: '総合スコア',
    stitle_programs: 'マイプログラム',
    btn_new: '新規',
    placeholder_prog_name: 'プログラム名...',
    btn_save_prog: '保存',
    label_prog_type: 'セッションタイプ（ログ用）',
    label_add_ex: '種目を追加',
    btn_add_list: 'リストに追加',
    stitle_content_block: '内容',
    stitle_gains: '獲得予測',
    label_gain_global: '推定総合獲得',
    btn_confirm_session: 'セッションを確定',
    btn_back: 'プログラムに戻る',
    stitle_stats: '統計データ',
    btn_export: 'エクスポート',
    btn_import: 'インポート',
    label_vol_total: '総ボリューム',
    label_sessions: 'セッション数',
    label_pr_done: '達成PR数',
    label_ex_diff: '種目数',
    label_ex_analyze: '種目分析',
    label_chart_vol: 'セッション別ボリューム',
    label_chart_pr: '推定1RM推移',
    label_chart_empty: '種目を選択してください',
    stitle_badges: 'バッジと進行状況',
    label_muscles: '筋肉部位',
    menu_home: 'RPG (ホーム)',
    menu_profil: 'プロフィール',
    menu_settings: '設定',
    label_prenom: '名',
    label_nom: '姓',
    label_age: '年齢',
    label_poids: '体重 (kg)',
    label_taille: '身長 (cm)',
    btn_save_profile: 'プロフィールを保存',
    label_lang: '言語',
    label_theme: 'テーマ',
    theme_dark: 'ダーク',
    theme_light: 'ライト',
    theme_amber: 'アンバー',
    lvl_avg: '平均レベル: ',
    lvl_keep_training: 'トレーニングを続けよう！',
    accumulated: '蓄積',
    hypertrophy: '筋肥大',
    strength: '筋力',
    hyperstrength: '最大筋力 (PR)',
    endurance: '筋持久力',
    deload: 'ディロード',
    pecs: '胸筋',
    back: '背筋',
    shoulders: '肩',
    biceps: '二頭筋',
    triceps: '三頭筋',
    quads: '大腿四頭筋',
    hams: 'ハムストリング',
    glutes: '臀筋',
    calves: 'ふくらはぎ',
    abs: '腹筋',
    lumbars: '腰部',
    traps: '僧帽筋',
    fullbody: '全身',
    sets: 'セット',
    no_sets: '記録がありません。<br>最初のセットを記録しましょう！',
    no_sets_filter: 'このフィルターに該当する記録はありません。',
    no_data: 'データなし',
    pr_on: '記録日:',
    edit: '編集',
    empty_list: 'リストが空です。',
    global_level: '総合レベル',
    level_up_global: '総合レベルアップ！',
    xp_left_for: 'レベル {{lvl}} まであと {{xp}} XP',
    xp_missing: 'あと {{xp}} XP 不足',
    all: 'すべて',
    exercises: '種目',
    achievements: '実績',
    special: 'スペシャル',
    career_stats: 'キャリア統計',
    records: '記録',
    unlocked_by: '全ユーザーの {{rate}} のみが解除',
    special_achievements: '特別実績',
    progress: '進捗',
    sessions: 'セッション',
    diff_exercises: '種目',
    choose_ex: '種目を選択',
    est_hybrid_1rm: '推定ハイブリッド1RM',
    p_7d: '直近7日間',
    p_30d: '直近30日間',
    p_90d: '直近90日間',
    p_1y: '1年間',
    p_all: 'すべて',
    profile_saved: 'プロフィールを保存しました！',
    lang_updated_to: '言語を更新しました',
    xp_left_for: 'レベル{{lvl}}まであと{{xp}} XP',
    xp_missing: '{{xp}} XP 不足',
    new_program: '新規プログラム',
    untitled: '無題',
    confirm_delete: '削除しますか？',
    confirm_session: 'セッションを確定しますか？',
    no_programs: 'プログラムがありません。'
  }

};
