/* ══════════════════════════════════════════════════════════════════════════
   MUSCU RPG — lang.js
   Internationalisation (i18n) — Support 5 langues
   Check-up complet v76
   ══════════════════════════════════════════════════════════════════════════ */

var I18N = {
  fr: {
    abs: 'Abdos',
    accumulated: 'accumulé',
    achievements: 'Succès',
    all: 'Tout',
    back: 'Dorsaux',
    biceps: 'Biceps',
    breaker_title: 'Briseur de Limites',
    btn_add_list: 'Ajouter à la liste',
    btn_back: 'Retour aux programmes',
    btn_confirm_session: 'Confirmer la séance (Log)',
    btn_export: 'Exporter',
    btn_import: 'Importer',
    btn_new: 'Nouveau',
    btn_save: 'Enregistrer',
    btn_save_profile: 'Enregistrer le Profil',
    btn_save_prog: 'Sauver',
    calves: 'Mollets',
    cameleon_title: 'Caméléon',
    career_stats: 'Statistiques de Carrière',
    chain_core: 'Core',
    chain_full_body: 'Full Body',
    chain_lower_ant: 'Bas Antérieur',
    chain_lower_post: 'Bas Postérieur',
    chain_upper_ant: 'Haut Antérieur',
    chain_upper_post: 'Haut Postérieur',
    choose_ex: 'Choisir un exercice',
    choose_exercise: 'Choisir un exercice',
    confirm_delete: 'Supprimer ce programme ?',
    confirm_session: 'Confirmer cette séance ?',
    deload: 'Décharge',
    endurance: 'Endurance musculaire',
    est_hybrid_1rm: '1RM estimé Hybride',
    exercises: 'Exercices',
    filter_all: 'Tout',
    filter_all_dates: '-- Toutes les dates --',
    filter_all_types: '-- Tous les types --',
    filter_date: 'Date',
    filter_ex: 'Exercice',
    filter_type: 'Type séance',
    fullbody: 'Full body',
    global_level: 'Niveau Global',
    glutes: 'Fessiers',
    hams: 'Ischios',
    hyperstrength: 'Hyperforce (PR)',
    hypertrophy: 'Hypertrophie',
    invalid_fields: 'Champs invalides',
    label_1rm_max: '1RM MAX',
    label_add_ex: 'Ajouter un exercice',
    label_age: 'Âge',
    label_chart_empty: 'Sélectionne un exercice pour voir son évolution',
    label_chart_pr: 'Évolution 1RM estimé',
    label_chart_vol: 'Volume par séance',
    label_date: 'Date',
    label_ex: 'Exercice',
    label_ex_analyze: 'Exercice à analyser',
    label_ex_diff: 'Exercices diff.',
    label_gain_global: 'Gain Global Estimé',
    label_lang: 'Langue',
    label_muscles: 'Groupes Musculaires',
    label_nom: 'Nom',
    label_pds: 'Poids (kg)',
    label_poids: 'Poids (kg)',
    label_pr_done: 'PR réalisés',
    label_prenom: 'Prénom',
    label_prog_type: 'Type de séance (appliqué au log)',
    label_rep: 'Répétitions',
    label_score_global: 'Score Global',
    label_ser: 'Séries',
    label_sessions: 'Séances',
    label_taille: 'Taille (cm)',
    label_theme: 'Thème Visuel',
    label_timer: 'Chrono de repos',
    label_type: 'Type de séance',
    label_vol_total: 'Volume total',
    lang_updated_to: 'Langue mise à jour',
    lumbars: 'Lombaires',
    lvl: 'Niveau',
    lvl_avg: 'Niveau moyen : ',
    lvl_keep_training: 'Continue à t\'entraîner !',
    lvl_up_global: 'NIVEAU GLOBAL SUPÉRIEUR !',
    menu_home: 'RPG (Accueil)',
    menu_profil: 'Profil',
    menu_settings: 'Paramètres',
    mono_title: 'Le Monolithe',
    new_program: 'Nouveau programme',
    no_data: 'Aucune donnée',
    no_programs: 'Aucun programme enregistré.',
    no_sets: 'Aucune série.<br>Saisis ta première entrée !',
    no_sets_filter: 'Aucune série pour ce filtre.',
    p_1y: '1 an',
    p_30d: '30 derniers jours',
    p_7d: '7 derniers jours',
    p_90d: '90 derniers jours',
    p_all: 'Tout',
    pecs: 'Pectoraux',
    pillar_title: 'Pilier de la Salle',
    placeholder_prog_name: 'Nom du programme...',
    pr_on: 'PR du',
    profile_saved: 'Profil enregistré !',
    prog_by_muscle: 'Progression par Muscle (RPG)',
    progress: 'Progression',
    quads: 'Quadriceps',
    rarity_common: 'COMMUN',
    rarity_epic: 'ÉPIQUE',
    rarity_legendary: 'LÉGENDAIRE',
    rarity_locked: 'BLOQUÉ',
    rarity_mythic: 'MYTHIQUE',
    rarity_rare: 'RARE',
    rarity_relic: 'RELIQUE',
    rarity_uncommon: 'PEU COMMUN',
    records: 'Records (PR)',
    saved: 'Sauvegardé',
    session_saved: 'Séance enregistrée !',
    sets: 'séries',
    shoulders: 'Épaules',
    slam_title: 'Grand Chelem Big 6',
    special: 'Spécial',
    special_achievements: 'Hauts Faits Spéciaux',
    stitle_badges: 'Badges & Progression',
    stitle_content_block: 'Contenu du bloc',
    stitle_gains: 'Prévisions de Gain',
    stitle_journal: 'Journal',
    stitle_new_serie: 'Nouvelle série',
    stitle_pr: 'PR — Big 6',
    stitle_pr_bonus: 'Analyse PR (Bonus)',
    stitle_programs: 'Mes Programmes',
    stitle_rpg: 'Progression RPG',
    stitle_stats: 'Statistiques',
    strength: 'Force',
    tab_badges: 'Badges',
    tab_pr: 'PR Big 6',
    tab_rpg: 'RPG',
    tab_seances: 'Séances',
    tab_simu: 'Simu',
    tab_stats: 'Stats',
    theme_amber: 'AMBRE',
    theme_dark: 'SOMBRE',
    theme_light: 'CLAIR',
    tier_athlete: 'Athlète',
    tier_divine: 'Divin',
    tier_expert: 'Expert',
    tier_inactive: 'Inactif',
    tier_initiate: 'Initié',
    tier_legend: 'Légende',
    tier_master: 'Maître',
    tier_novice: 'Novice',
    timer_reset: 'Reset',
    timer_start: 'Démarrer',
    timer_stop: 'Arrêter',
    titan_title: 'Titan du Volume',
    traps: 'Trapèzes',
    triceps: 'Triceps',
    unit_exercises: 'exercices',
    unit_reps: 'reps',
    unit_sessions: 'séances',
    unlocked_by: 'Débloqué par seulement {{rate}} des athlètes',
    untitled: 'Sans titre',
    worker_title: 'Acharne du Travail',
    xp_left_for: 'Encore {{xp}} XP pour le Niv. {{lvl}}',
    xp_missing: '{{xp}} XP manquants',

    // ── EXERCICES (CLEFS FR) ──
    'Ab wheel (roue abdominale)': 'Ab wheel (roue abdominale)',
    'Abduction hanche câble': 'Abduction hanche câble',
    'Abduction machine': 'Abduction machine',
    'Arnold press': 'Arnold press',
    'Barre explosive (power clean)': 'Barre explosive (power clean)',
    'Biceps poulie 1 bras': 'Biceps poulie 1 bras',
    'Burpee avec développé': 'Burpee avec développé',
    'Cable crunch poulie haute': 'Cable crunch poulie haute',
    'Crossover câble': 'Crossover câble',
    'Crunch': 'Crunch',
    'Crunch machine': 'Crunch machine',
    'Curl barre EZ': 'Curl barre EZ',
    'Curl barre droite': 'Curl barre droite',
    'Curl câble haute poulie': 'Curl câble haute poulie',
    'Curl haltères alternés': 'Curl haltères alternés',
    'Curl incliné haltères': 'Curl incliné haltères',
    'Curl marteau': 'Curl marteau',
    'Curl pupitre / Scott': 'Curl pupitre / Scott',
    'Dips': 'Dips',
    'Développé couché barre': 'Développé couché barre',
    'Développé couché haltères': 'Développé couché haltères',
    'Développé couché prise serrée': 'Développé couché prise serrée',
    'Développé décliné barre': 'Développé décliné barre',
    'Développé incliné barre': 'Développé incliné barre',
    'Développé incliné haltères': 'Développé incliné haltères',
    'Développé machine': 'Développé machine',
    'Développé militaire barre': 'Développé militaire barre',
    'Développé militaire haltères': 'Développé militaire haltères',
    'Extensions lombaires banc romain': 'Extensions lombaires banc romain',
    'Extensions triceps poulie haute': 'Extensions triceps poulie haute',
    'Face pull câble': 'Face pull câble',
    'Fentes arrière accent ischio': 'Fentes arrière accent ischio',
    'Fentes arrière haltères': 'Fentes arrière haltères',
    'Fentes avant haltères': 'Fentes avant haltères',
    'Fentes latérales': 'Fentes latérales',
    'Fentes marchées': 'Fentes marchées',
    'Gainage face (planche)': 'Gainage face (planche)',
    'Gainage latéral': 'Gainage latéral',
    'Glute bridge au sol': 'Glute bridge au sol',
    'Good morning barre': 'Good morning barre',
    'Hack squat machine': 'Hack squat machine',
    'Hip thrust barre': 'Hip thrust barre',
    'Hip thrust machine': 'Hip thrust machine',
    'Kickback fessier câble': 'Kickback fessier câble',
    'Kickback triceps haltère': 'Kickback triceps haltère',
    'Leg curl assis machine': 'Leg curl assis machine',
    'Leg curl couché machine': 'Leg curl couché machine',
    'Leg curl debout câble': 'Leg curl debout câble',
    'Leg extension machine': 'Leg extension machine',
    'Leg press 45°': 'Leg press 45°',
    'Mollets assis machine': 'Mollets assis machine',
    'Mollets debout machine': 'Mollets debout machine',
    'Mollets haltères 1 jambe': 'Mollets haltères 1 jambe',
    'Mollets presse à jambes': 'Mollets presse à jambes',
    'Mollets à la barre': 'Mollets à la barre',
    'Nordic curl': 'Nordic curl',
    'Oiseau haltères': 'Oiseau haltères',
    'Pompes': 'Pompes',
    'Pompes prise serrée': 'Pompes prise serrée',
    'Presse épaule machine': 'Presse épaule machine',
    'Pull over haltère': 'Pull over haltère',
    'Pull over poulie': 'Pull over poulie',
    'Relevé de buste banc décliné': 'Relevé de buste banc décliné',
    'Relevé de jambes suspendu': 'Relevé de jambes suspendu',
    'Rotation externe câble': 'Rotation externe câble',
    'Rotation russe': 'Rotation russe',
    'Rowing barre': 'Rowing barre',
    'Rowing haltère 1 bras': 'Rowing haltère 1 bras',
    'Rowing machine': 'Rowing machine',
    'Rowing vertical / Upright row': 'Rowing vertical / Upright row',
    'Shrugs barre': 'Shrugs barre',
    'Shrugs haltères': 'Shrugs haltères',
    'Shrugs machine': 'Shrugs machine',
    'Sissy squat': 'Sissy squat',
    'Skull crusher barre': 'Skull crusher barre',
    'Soulevé de terre complet': 'Soulevé de terre complet',
    'Soulevé de terre conventionnel': 'Soulevé de terre conventionnel',
    'Soulevé de terre roumain': 'Soulevé de terre roumain',
    'Soulevé de terre sumo': 'Soulevé de terre sumo',
    'Squat avant (front squat)': 'Squat avant (front squat)',
    'Squat barre': 'Squat barre',
    'Squat gobelet haltère': 'Squat gobelet haltère',
    'Squat sauté': 'Squat sauté',
    'Step up haltères': 'Step up haltères',
    'Sumo squat haltère': 'Sumo squat haltère',
    'Superman': 'Superman',
    'Tirage allongé poulie basse': 'Tirage allongé poulie basse',
    'Tirage bras tendu câble': 'Tirage bras tendu câble',
    'Tirage haut kimono': 'Tirage haut kimono',
    'Tirage poitrine poulie haute': 'Tirage poitrine poulie haute',
    'Traction haute kimono isométrique': 'Traction haute kimono isométrique',
    'Tractions neutres': 'Tractions neutres',
    'Tractions pronation': 'Tractions pronation',
    'Tractions supination': 'Tractions supination',
    'Triceps machine': 'Triceps machine',
    'Triceps poulie 1 bras': 'Triceps poulie 1 bras',
    'Écarté haltères': 'Écarté haltères',
    'Écarté machine / Pec deck': 'Écarté machine / Pec deck',
    'Élévation frontale haltères': 'Élévation frontale haltères',
    'Élévation latérale câble': 'Élévation latérale câble',
    'Élévation latérale haltères': 'Élévation latérale haltères',
  },
  en: {
    abs: 'Abs',
    accumulated: 'accumulated',
    achievements: 'Achievements',
    all: 'All',
    back: 'Back',
    biceps: 'Biceps',
    breaker_title: 'Limit Breaker',
    btn_add_list: 'Add to List',
    btn_back: 'Back to Programs',
    btn_confirm_session: 'Confirm Session (Log)',
    btn_export: 'Export',
    btn_import: 'Import',
    btn_new: 'New',
    btn_save: 'Save',
    btn_save_profile: 'Save Profile',
    btn_save_prog: 'Save',
    calves: 'Calves',
    cameleon_title: 'Chameleon',
    career_stats: 'Career Statistics',
    chain_core: 'Core',
    chain_full_body: 'Full Body',
    chain_lower_ant: 'Lower Anterior',
    chain_lower_post: 'Lower Posterior',
    chain_upper_ant: 'Upper Anterior',
    chain_upper_post: 'Upper Posterior',
    choose_ex: 'Choose an exercise',
    choose_exercise: 'Choose an exercise',
    confirm_delete: 'Delete this program?',
    confirm_session: 'Confirm this session?',
    deload: 'Deload',
    endurance: 'Muscular Endurance',
    est_hybrid_1rm: 'Est. Hybrid 1RM',
    exercises: 'Exercises',
    filter_all: 'All',
    filter_all_dates: '-- All dates --',
    filter_all_types: '-- All types --',
    filter_date: 'Date',
    filter_ex: 'Exercise',
    filter_type: 'Type',
    fullbody: 'Full Body',
    global_level: 'Global Level',
    glutes: 'Glutes',
    hams: 'Hamstrings',
    hyperstrength: 'Hyperstrength (PR)',
    hypertrophy: 'Hypertrophy',
    invalid_fields: 'Invalid fields',
    label_1rm_max: '1RM MAX',
    label_add_ex: 'Add Exercise',
    label_age: 'Age',
    label_chart_empty: 'Select an exercise to see progress',
    label_chart_pr: 'Estimated 1RM trend',
    label_chart_vol: 'Volume per session',
    label_date: 'Date',
    label_ex: 'Exercise',
    label_ex_analyze: 'Analyze Exercise',
    label_ex_diff: 'Diff. Exercises',
    label_gain_global: 'Est. Global Gain',
    label_lang: 'Language',
    label_muscles: 'Muscle Groups',
    label_nom: 'Last Name',
    label_pds: 'Weight (kg)',
    label_poids: 'Weight (kg)',
    label_pr_done: 'PRs achieved',
    label_prenom: 'First Name',
    label_prog_type: 'Session Type (for log)',
    label_rep: 'Reps',
    label_score_global: 'Global Score',
    label_ser: 'Sets',
    label_sessions: 'Sessions',
    label_taille: 'Height (cm)',
    label_theme: 'Visual Theme',
    label_timer: 'Rest Timer',
    label_type: 'Session Type',
    label_vol_total: 'Total Volume',
    lang_updated_to: 'Language updated',
    lumbars: 'Lower Back',
    lvl: 'Level',
    lvl_avg: 'Average Level: ',
    lvl_keep_training: 'Keep training!',
    lvl_up_global: 'GLOBAL LEVEL UP!',
    menu_home: 'RPG (Home)',
    menu_profil: 'Profile',
    menu_settings: 'Settings',
    mono_title: 'The Monolith',
    new_program: 'New Program',
    no_data: 'No data',
    no_programs: 'No programs saved.',
    no_sets: 'No sets found.<br>Enter your first session!',
    no_sets_filter: 'No sets for this filter.',
    p_1y: '1 year',
    p_30d: 'Last 30 days',
    p_7d: 'Last 7 days',
    p_90d: 'Last 90 days',
    p_all: 'All',
    pecs: 'Chest',
    pillar_title: 'Gym Pillar',
    placeholder_prog_name: 'Program name...',
    pr_on: 'PR on',
    profile_saved: 'Profile saved!',
    prog_by_muscle: 'Progress by Muscle (RPG)',
    progress: 'Progress',
    quads: 'Quads',
    rarity_common: 'COMMON',
    rarity_epic: 'EPIC',
    rarity_legendary: 'LEGENDARY',
    rarity_locked: 'LOCKED',
    rarity_mythic: 'MYTHIC',
    rarity_rare: 'RARE',
    rarity_relic: 'RELIC',
    rarity_uncommon: 'UNCOMMON',
    records: 'Records (PR)',
    saved: 'Saved',
    session_saved: 'Session saved!',
    sets: 'sets',
    shoulders: 'Shoulders',
    slam_title: 'Big 6 Grand Slam',
    special: 'Special',
    special_achievements: 'Special Achievements',
    stitle_badges: 'Badges & Progress',
    stitle_content_block: 'Block Content',
    stitle_gains: 'Gain Forecast',
    stitle_journal: 'Journal',
    stitle_new_serie: 'New Set',
    stitle_pr: 'PR — Big 6',
    stitle_pr_bonus: 'PR Analysis (Bonus)',
    stitle_programs: 'My Programs',
    stitle_rpg: 'RPG Progression',
    stitle_stats: 'Statistics',
    strength: 'Strength',
    tab_badges: 'Badges',
    tab_pr: 'PR Big 6',
    tab_rpg: 'RPG',
    tab_seances: 'Logs',
    tab_simu: 'Simu',
    tab_stats: 'Stats',
    theme_amber: 'AMBER',
    theme_dark: 'DARK',
    theme_light: 'LIGHT',
    tier_athlete: 'Athlete',
    tier_divine: 'Divine',
    tier_expert: 'Expert',
    tier_inactive: 'Inactive',
    tier_initiate: 'Initiate',
    tier_legend: 'Legend',
    tier_master: 'Master',
    tier_novice: 'Novice',
    timer_reset: 'Reset',
    timer_start: 'Start',
    timer_stop: 'Stop',
    titan_title: 'Volume Titan',
    traps: 'Traps',
    triceps: 'Triceps',
    unit_exercises: 'exercises',
    unit_reps: 'reps',
    unit_sessions: 'sessions',
    unlocked_by: 'Unlocked by only {{rate}} of athletes',
    untitled: 'Untitled',
    worker_title: 'Hard Worker',
    xp_left_for: '{{xp}} XP left for Lvl {{lvl}}',
    xp_missing: '{{xp}} XP missing',

    // ── EXERCICES (CLEFS FR) ──
    'Ab wheel (roue abdominale)': 'Ab Wheel',
    'Abduction hanche câble': 'Cable Hip Abduction',
    'Abduction machine': 'Machine Hip Abduction',
    'Arnold press': 'Arnold Press',
    'Barre explosive (power clean)': 'Power Clean',
    'Biceps poulie 1 bras': 'Single Arm Cable Curl',
    'Burpee avec développé': 'Burpee with Press',
    'Cable crunch poulie haute': 'Cable Crunch',
    'Crossover câble': 'Cable Cross Over',
    'Crunch': 'Crunch',
    'Crunch machine': 'Machine Crunch',
    'Curl barre EZ': 'EZ Bar Curl',
    'Curl barre droite': 'Straight Bar Curl',
    'Curl câble haute poulie': 'High Cable Curl',
    'Curl haltères alternés': 'Alternating Dumbbell Curl',
    'Curl incliné haltères': 'Incline Dumbbell Curl',
    'Curl marteau': 'Hammer Curl',
    'Curl pupitre / Scott': 'Preacher Curl',
    'Dips': 'Dips',
    'Développé couché barre': 'Barbell Bench Press',
    'Développé couché haltères': 'Dumbbell Bench Press',
    'Développé couché prise serrée': 'Close Grip Bench Press',
    'Développé décliné barre': 'Decline Barbell Bench Press',
    'Développé incliné barre': 'Incline Barbell Bench Press',
    'Développé incliné haltères': 'Incline Dumbbell Bench Press',
    'Développé machine': 'Machine Chest Press',
    'Développé militaire barre': 'Barbell Military Press',
    'Développé militaire haltères': 'Dumbbell Military Press',
    'Extensions lombaires banc romain': 'Back Extension',
    'Extensions triceps poulie haute': 'Triceps Pushdown',
    'Face pull câble': 'Cable Face Pull',
    'Fentes arrière accent ischio': 'Glute-focused Backward Lunge',
    'Fentes arrière haltères': 'Dumbbell Backward Lunge',
    'Fentes avant haltères': 'Dumbbell Forward Lunge',
    'Fentes latérales': 'Side Lunges',
    'Fentes marchées': 'Walking Lunges',
    'Gainage face (planche)': 'Plank',
    'Gainage latéral': 'Side Plank',
    'Glute bridge au sol': 'Glute Bridge',
    'Good morning barre': 'Barbell Good Morning',
    'Hack squat machine': 'Hack Squat Machine',
    'Hip thrust barre': 'Barbell Hip Thrust',
    'Hip thrust machine': 'Machine Hip Thrust',
    'Kickback fessier câble': 'Cable Glute Kickback',
    'Kickback triceps haltère': 'Dumbbell Triceps Kickback',
    'Leg curl assis machine': 'Seated Leg Curl',
    'Leg curl couché machine': 'Lying Leg Curl',
    'Leg curl debout câble': 'Standing Cable Leg Curl',
    'Leg extension machine': 'Leg Extension Machine',
    'Leg press 45°': '45° Leg Press',
    'Mollets assis machine': 'Seated Calf Raise Machine',
    'Mollets debout machine': 'Standing Calf Raise Machine',
    'Mollets haltères 1 jambe': 'Single Leg Dumbbell Calf Raise',
    'Mollets presse à jambes': 'Leg Press Calf Raise',
    'Mollets à la barre': 'Barbell Calf Raise',
    'Nordic curl': 'Nordic Curl',
    'Oiseau haltères': 'Rear Delt Flyes',
    'Pompes': 'Push-ups',
    'Pompes prise serrée': 'Close Grip Push-ups',
    'Presse épaule machine': 'Machine Shoulder Press',
    'Pull over haltère': 'Dumbbell Pullover',
    'Pull over poulie': 'Cable Pullover',
    'Relevé de buste banc décliné': 'Decline Sit-ups',
    'Relevé de jambes suspendu': 'Hanging Leg Raise',
    'Rotation externe câble': 'Cable External Rotation',
    'Rotation russe': 'Russian Twist',
    'Rowing barre': 'Barbell Row',
    'Rowing haltère 1 bras': 'One Arm Dumbbell Row',
    'Rowing machine': 'Machine Row',
    'Rowing vertical / Upright row': 'Upright Row',
    'Shrugs barre': 'Barbell Shrugs',
    'Shrugs haltères': 'Dumbbell Shrugs',
    'Shrugs machine': 'Machine Shrugs',
    'Sissy squat': 'Sissy Squat',
    'Skull crusher barre': 'Skull Crushers',
    'Soulevé de terre complet': 'Full Deadlift',
    'Soulevé de terre conventionnel': 'Conventional Deadlift',
    'Soulevé de terre roumain': 'Romanian Deadlift',
    'Soulevé de terre sumo': 'Sumo Deadlift',
    'Squat avant (front squat)': 'Front Squat',
    'Squat barre': 'Barbell Squat',
    'Squat gobelet haltère': 'Dumbbell Goblet Squat',
    'Squat sauté': 'Jump Squat',
    'Step up haltères': 'Dumbbell Step-up',
    'Sumo squat haltère': 'Dumbbell Sumo Squat',
    'Superman': 'Superman',
    'Tirage allongé poulie basse': 'Seated Cable Row',
    'Tirage bras tendu câble': 'Straight Arm Lat Pulldown',
    'Tirage haut kimono': 'Lat Pulldown (Kimono)',
    'Tirage poitrine poulie haute': 'Lat Pulldown',
    'Traction haute kimono isométrique': 'Isometric Kimono Hold',
    'Tractions neutres': 'Neutral Grip Pull-ups',
    'Tractions pronation': 'Pull-ups',
    'Tractions supination': 'Chin-ups',
    'Triceps machine': 'Triceps Extension Machine',
    'Triceps poulie 1 bras': 'Single Arm Triceps Pushdown',
    'Écarté haltères': 'Dumbbell Flyes',
    'Écarté machine / Pec deck': 'Pec Deck Machine',
    'Élévation frontale haltères': 'Dumbbell Front Raise',
    'Élévation latérale câble': 'Cable Lateral Raise',
    'Élévation latérale haltères': 'Dumbbell Lateral Raise',
  },
  de: {
    abs: 'Bauchmuskeln',
    accumulated: 'akkumuliert',
    achievements: 'Erfolge',
    all: 'Alle',
    back: 'Rücken',
    biceps: 'Bizeps',
    breaker_title: 'Grenzbrecher',
    btn_add_list: 'Zur Liste hinzufügen',
    btn_back: 'Zurück zu Programmen',
    btn_confirm_session: 'Sitzung bestätigen (Log)',
    btn_export: 'Exportieren',
    btn_import: 'Importieren',
    btn_new: 'Neu',
    btn_save: 'Speichern',
    btn_save_profile: 'Profil speichern',
    btn_save_prog: 'Speichern',
    calves: 'Waden',
    cameleon_title: 'Chamäleon',
    career_stats: 'Karrierestatistiken',
    chain_core: 'Rumpf',
    chain_full_body: 'Ganzkörper',
    chain_lower_ant: 'Unterkörper Vorne',
    chain_lower_post: 'Unterkörper Hinten',
    chain_upper_ant: 'Oberkörper Vorne',
    chain_upper_post: 'Oberkörper Hinten',
    choose_ex: 'Übung wählen',
    choose_exercise: 'Übung wählen',
    confirm_delete: 'Programm löschen?',
    confirm_session: 'Sitzung bestätigen?',
    deload: 'Entlastung',
    endurance: 'Kraftausdauer',
    est_hybrid_1rm: 'Gesch. Hybrid 1RM',
    exercises: 'Übungen',
    filter_all: 'Alle',
    filter_all_dates: '-- Alle Daten --',
    filter_all_types: '-- Alle Typen --',
    filter_date: 'Datum',
    filter_ex: 'Übung',
    filter_type: 'Typ',
    fullbody: 'Ganzkörper',
    global_level: 'Gesamtlevel',
    glutes: 'Gesäß',
    hams: 'Beinbeuger',
    hyperstrength: 'Hyperkraft (PR)',
    hypertrophy: 'Hypertrophie',
    invalid_fields: 'Ungültige Felder',
    label_1rm_max: '1RM MAX',
    label_add_ex: 'Übung hinzufügen',
    label_age: 'Alter',
    label_chart_empty: 'Wähle eine Übung, um den Fortschritt zu sehen',
    label_chart_pr: 'Trend 1RM geschätzt',
    label_chart_vol: 'Volumen pro Sitzung',
    label_date: 'Datum',
    label_ex: 'Übung',
    label_ex_analyze: 'Übung analysieren',
    label_ex_diff: 'Verschiedene Übungen',
    label_gain_global: 'Gesch. Gesamtgewinn',
    label_lang: 'Sprache',
    label_muscles: 'Muskelgruppen',
    label_nom: 'Nachname',
    label_pds: 'Gewicht (kg)',
    label_poids: 'Gewicht (kg)',
    label_pr_done: 'PRs erreicht',
    label_prenom: 'Vorname',
    label_prog_type: 'Sitzungstyp (für Log)',
    label_rep: 'Wdh',
    label_score_global: 'Gesamtpunktzahl',
    label_ser: 'Sätze',
    label_sessions: 'Sitzungen',
    label_taille: 'Größe (cm)',
    label_theme: 'Design',
    label_timer: 'Pause-Timer',
    label_type: 'Sitzungstyp',
    label_vol_total: 'Gesamtvolumen',
    lang_updated_to: 'Sprache aktualisiert',
    lumbars: 'Unterer Rücken',
    lvl: 'Level',
    lvl_avg: 'Durchschnittsstufe: ',
    lvl_keep_training: 'Trainiere weiter!',
    lvl_up_global: 'GESAMTLEVEL UP!',
    menu_home: 'RPG (Home)',
    menu_profil: 'Profile',
    menu_settings: 'Einstellungen',
    mono_title: 'Der Monolith',
    new_program: 'Neues Programm',
    no_data: 'Keine Daten',
    no_programs: 'Keine Programme gespeichert.',
    no_sets: 'Keine Sätze gefunden.<br>Gib deine erste Sitzung ein!',
    no_sets_filter: 'Keine Sätze für diesen Filter.',
    p_1y: '1 Jahr',
    p_30d: 'Letzte 30 Tage',
    p_7d: 'Letzte 7 Tage',
    p_90d: 'Letzte 90 Tage',
    p_all: 'Alle',
    pecs: 'Brust',
    pillar_title: 'Fitness-Säule',
    placeholder_prog_name: 'Programmname...',
    pr_on: 'PR am',
    profile_saved: 'Profil gespeichert!',
    prog_by_muscle: 'Fortschritt pro Muskel (RPG)',
    progress: 'Fortschritt',
    quads: 'Quads',
    rarity_common: 'GEWÖHNLICH',
    rarity_epic: 'EPISCH',
    rarity_legendary: 'LEGENDÄR',
    rarity_locked: 'GESPERRT',
    rarity_mythic: 'MYTHISCH',
    rarity_rare: 'SELTEN',
    rarity_relic: 'RELIKT',
    rarity_uncommon: 'UNGEWÖHNLICH',
    records: 'Rekorde (PR)',
    saved: 'Gespeichert',
    session_saved: 'Sitzung gespeichert!',
    sets: 'Sätze',
    shoulders: 'Schultern',
    slam_title: 'Big 6 Grand Slam',
    special: 'Spezial',
    special_achievements: 'Besondere Erfolge',
    stitle_badges: 'Badges & Fortschritt',
    stitle_content_block: 'Blockinhalt',
    stitle_gains: 'Gewinnprognose',
    stitle_journal: 'Journal',
    stitle_new_serie: 'Neuer Satz',
    stitle_pr: 'PR — Big 6',
    stitle_programs: 'Meine Programme',
    stitle_rpg: 'RPG Fortschritt',
    stitle_stats: 'Statistiken',
    strength: 'Kraft',
    tab_badges: 'Badges',
    tab_pr: 'PR Big 6',
    tab_rpg: 'RPG',
    tab_seances: 'Sitzungen',
    tab_simu: 'Simu',
    tab_stats: 'Stats',
    theme_amber: 'BERNSTEIN',
    theme_dark: 'DUNKEL',
    theme_light: 'HELL',
    tier_athlete: 'Athlet',
    tier_divine: 'Göttlich',
    tier_expert: 'Experte',
    tier_inactive: 'Inaktiv',
    tier_initiate: 'Eingeweiht',
    tier_legend: 'Legende',
    tier_master: 'Meister',
    tier_novice: 'Anfänger',
    timer_reset: 'Reset',
    timer_start: 'Start',
    timer_stop: 'Stopp',
    titan_title: 'Volumen-Titan',
    traps: 'Nacken',
    triceps: 'Trizeps',
    unit_exercises: 'Übungen',
    unit_reps: 'Wdh',
    unit_sessions: 'Sitzungen',
    unlocked_by: 'Freigeschaltet von nur {{rate}} der Athleten',
    untitled: 'Unbenannt',
    worker_title: 'Fleißiger Arbeiter',
    xp_left_for: 'Noch {{xp}} XP bis Level {{lvl}}',
    xp_missing: '{{xp}} XP fehlen',

    // ── EXERCICES (CLEFS FR) ──
    'Ab wheel (roue abdominale)': 'Ab Wheel',
    'Abduction hanche câble': 'Hüftabduktion Kabelzug',
    'Abduction machine': 'Abduktionsmaschine',
    'Arnold press': 'Arnold Press',
    'Barre explosive (power clean)': 'Umsetzen',
    'Biceps poulie 1 bras': 'Einarmiger Kabelcurl',
    'Burpee avec développé': 'Burpees mit Drücken',
    'Cable crunch poulie haute': 'Kabel-Crunch',
    'Crossover câble': 'Cable Cross',
    'Crunch': 'Crunch',
    'Crunch machine': 'Bauchpresse Maschine',
    'Curl barre EZ': 'SZ-Hantelcurl',
    'Curl barre droite': 'Langhantelcurl',
    'Curl câble haute poulie': 'Kabelcurls hoch',
    'Curl haltères alternés': 'Abwechselnde Kurzhantelcurls',
    'Curl incliné haltères': 'Schrägbank-Curls',
    'Curl marteau': 'Hammercurls',
    'Curl pupitre / Scott': 'Preacher Curls',
    'Dips': 'Barrenstütz',
    'Développé couché barre': 'Bankdrücken Langhantel',
    'Développé couché haltères': 'Bankdrücken Kurzhantel',
    'Développé couché prise serrée': 'Enges Bankdrücken',
    'Développé décliné barre': 'Negativbankdrücken Langhantel',
    'Développé incliné barre': 'Schrägbankdrücken Langhantel',
    'Développé incliné haltères': 'Schrägbankdrücken Kurzhantel',
    'Développé machine': 'Brustpresse Maschine',
    'Développé militaire barre': 'Military Press Langhantel',
    'Développé militaire haltères': 'Schulterdrücken Kurzhantel',
    'Extensions lombaires banc romain': 'Hyperextensions',
    'Extensions triceps poulie haute': 'Trizepsdrücken Kabelzug',
    'Face pull câble': 'Face Pulls Kabelzug',
    'Fentes arrière accent ischio': 'Ausfallschritte hinten (Ischio)',
    'Fentes arrière haltères': 'Ausfallschritte nach hinten',
    'Fentes avant haltères': 'Ausfallschritte nach vorne',
    'Fentes latérales': 'Seitliche Ausfallschritte',
    'Fentes marchées': 'Ausfallschritte gehend',
    'Gainage face (planche)': 'Unterarmstütz',
    'Gainage latéral': 'Seitstütz',
    'Glute bridge au sol': 'Glute Bridge',
    'Good morning barre': 'Good Mornings',
    'Hack squat machine': 'Hackenschmidt-Maschine',
    'Hip thrust barre': 'Hip Thrust Langhantel',
    'Hip thrust machine': 'Hip Thrust Maschine',
    'Kickback fessier câble': 'Glute-Kickbacks Kabelzug',
    'Kickback triceps haltère': 'Trizeps-Kickbacks',
    'Leg curl assis machine': 'Beinbeuger sitzend',
    'Leg curl couché machine': 'Beinbeuger liegend',
    'Leg curl debout câble': 'Beinbeuger de pie en polea',
    'Leg extension machine': 'Beinstrecker Maschine',
    'Leg press 45°': 'Beinpresse 45°',
    'Mollets assis machine': 'Wadenheben sitzend',
    'Mollets debout machine': 'Wadenheben stehend',
    'Mollets haltères 1 jambe': 'Einbeiniges Wadenheben',
    'Mollets presse à jambes': 'Wadenheben an der Beinpresse',
    'Mollets à la barre': 'Wadenheben Langhantel',
    'Nordic curl': 'Nordic Curls',
    'Oiseau haltères': 'Vorgebeugtes Seitheben',
    'Pompes': 'Liegestütze',
    'Pompes prise serrée': 'Liegestütze enger Griff',
    'Presse épaule machine': 'Schulterpresse Maschine',
    'Pull over haltère': 'Überzüge Kurzhantel',
    'Pull over poulie': 'Überzüge Kabelzug',
    'Relevé de buste banc décliné': 'Sit-ups auf der Negativbank',
    'Relevé de jambes suspendu': 'Beinheben hängend',
    'Rotation externe câble': 'Außenrotation Kabelzug',
    'Rotation russe': 'Russian Twist',
    'Rowing barre': 'Langhantelrudern',
    'Rowing haltère 1 bras': 'Einarmiges Kurzhantelrudern',
    'Rowing machine': 'Rudermaschine',
    'Rowing vertical / Upright row': 'Aufrechtes Rudern',
    'Shrugs barre': 'Langhantel-Shrugs',
    'Shrugs haltères': 'Kurzhantel-Shrugs',
    'Shrugs machine': 'Shrugs Maschine',
    'Sissy squat': 'Sissy Squat',
    'Skull crusher barre': 'Skull Crusher',
    'Soulevé de terre complet': 'Kreuzheben komplett',
    'Soulevé de terre conventionnel': 'Kreuzheben konventionell',
    'Soulevé de terre roumain': 'Rumänisches Kreuzheben',
    'Soulevé de terre sumo': 'Sumo-Kreuzheben',
    'Squat avant (front squat)': 'Frontkniebeuge',
    'Squat barre': 'Langhantel-Kniebeuge',
    'Squat gobelet haltère': 'Goblet Squat',
    'Squat sauté': 'Squat Jumps',
    'Step up haltères': 'Step-ups Kurzhantel',
    'Sumo squat haltère': 'Sumo Squat Kurzhantel',
    'Superman': 'Superman',
    'Tirage allongé poulie basse': 'Rudern am Kabelzug',
    'Tirage bras tendu câble': 'Überzüge am Kabelzug',
    'Tirage haut kimono': 'Latzug (Kimono)',
    'Tirage poitrine poulie haute': 'Latzug zur Brust',
    'Traction haute kimono isométrique': 'Isometrisches Halten (Kimono)',
    'Tractions neutres': 'Klimmzüge Neutralgriff',
    'Tractions pronation': 'Klimmzüge Obergriff',
    'Tractions supination': 'Klimmzüge Untergriff',
    'Triceps machine': 'Trizeps-Maschine',
    'Triceps poulie 1 bras': 'Einarmiges Trizepsdrücken',
    'Écarté haltères': 'Fliegende Kurzhantel',
    'Écarté machine / Pec deck': 'Pec Deck Maschine',
    'Élévation frontale haltères': 'Frontheben Kurzhantel',
    'Élévation latérale câble': 'Seitheben Kabelzug',
    'Élévation latérale haltères': 'Seitheben Kurzhantel',
  },
  es: {
    abs: 'Abdominales',
    accumulated: 'acumulado',
    achievements: 'Logros',
    all: 'Todo',
    back: 'Espalda',
    biceps: 'Bíceps',
    breaker_title: 'Rompedor de Límites',
    btn_add_list: 'Añadir a la lista',
    btn_back: 'Volver a programas',
    btn_confirm_session: 'Confirmar sesión (Log)',
    btn_export: 'Exportar',
    btn_import: 'Importar',
    btn_new: 'Nuevo',
    btn_save: 'Guardar',
    btn_save_profile: 'Guardar Perfil',
    btn_save_prog: 'Guardar',
    calves: 'Gemelos',
    cameleon_title: 'Camaleón',
    career_stats: 'Estadísticas de Carrera',
    chain_core: 'Núcleo',
    chain_full_body: 'Cuerpo Completo',
    chain_lower_ant: 'Parte Inferior Anterior',
    chain_lower_post: 'Parte Inferior Posterior',
    chain_upper_ant: 'Parte Superior Anterior',
    chain_upper_post: 'Parte Superior Posterior',
    choose_ex: 'Elegir ejercicio',
    choose_exercise: 'Elegir un ejercicio',
    confirm_delete: '¿Eliminar este programa?',
    confirm_session: '¿Confirmar sesión?',
    deload: 'Descarga',
    endurance: 'Resistencia muscular',
    est_hybrid_1rm: '1RM est. Híbrido',
    exercises: 'Ejercicios',
    filter_all: 'Todo',
    filter_all_dates: '-- Todas las fechas --',
    filter_all_types: '-- Todos los tipos --',
    filter_date: 'Fecha',
    filter_ex: 'Ejercicio',
    filter_type: 'Tipo',
    fullbody: 'Cuerpo completo',
    global_level: 'Nivel Global',
    glutes: 'Glúteos',
    hams: 'Isquios',
    hyperstrength: 'Hiperfuerza (PR)',
    hypertrophy: 'Hipertrofia',
    invalid_fields: 'Campos inválidos',
    label_1rm_max: '1RM MAX',
    label_add_ex: 'Añadir Ejercicio',
    label_age: 'Edad',
    label_chart_empty: 'Selecciona un ejercicio para ver el progreso',
    label_chart_pr: 'Tendencia 1RM est.',
    label_chart_vol: 'Volumen por sesión',
    label_date: 'Fecha',
    label_ex: 'Ejercicio',
    label_ex_analyze: 'Analizar ejercicio',
    label_ex_diff: 'Ejercicios dif.',
    label_gain_global: 'Ganancia Global Est.',
    label_lang: 'Idioma',
    label_muscles: 'Grupos Musculares',
    label_nom: 'Apellido',
    label_pds: 'Peso (kg)',
    label_poids: 'Peso (kg)',
    label_pr_done: 'PRs realizados',
    label_prenom: 'Nombre',
    label_prog_type: 'Tipo de sesión (para el log)',
    label_rep: 'Reps',
    label_score_global: 'Puntuación Global',
    label_ser: 'Series',
    label_sessions: 'Sesiones',
    label_taille: 'Altura (cm)',
    label_theme: 'Tema',
    label_timer: 'Temporizador',
    label_type: 'Tipo de Sesión',
    label_vol_total: 'Volumen total',
    lang_updated_to: 'Idioma actualizado',
    lumbars: 'Lumbares',
    lvl: 'Nivel',
    lvl_avg: 'Nivel medio: ',
    lvl_keep_training: '¡Sigue entrenando!',
    lvl_up_global: '¡NIVEL GLOBAL SUPERADO!',
    menu_home: 'RPG (Home)',
    menu_profil: 'Perfil',
    menu_settings: 'Ajustes',
    mono_title: 'El Monolito',
    new_program: 'Nuevo Programa',
    no_data: 'Sin datos',
    no_programs: 'No hay programas guardados.',
    no_sets: 'No se encontraron series.<br>¡Registra tu primera sesión!',
    no_sets_filter: 'No hay series para este filtro.',
    p_1y: '1 año',
    p_30d: 'Últimos 30 días',
    p_7d: 'Últimos 7 días',
    p_90d: 'Últimos 90 días',
    p_all: 'Todo',
    pecs: 'Pectorales',
    pillar_title: 'Pilar del Gimnasio',
    placeholder_prog_name: 'Nombre del programa...',
    pr_on: 'PR el',
    profile_saved: '¡Perfil guardado!',
    prog_by_muscle: 'Progresión por Músculo (RPG)',
    progress: 'Progresión',
    quads: 'Cuádriceps',
    rarity_common: 'COMÚN',
    rarity_epic: 'ÉPICO',
    rarity_legendary: 'LEGENDARIO',
    rarity_locked: 'BLOQUEADO',
    rarity_mythic: 'MÍTICO',
    rarity_rare: 'RARO',
    rarity_relic: 'RELIQUIA',
    rarity_uncommon: 'POCO COMÚN',
    records: 'Récords (PR)',
    saved: 'Guardado',
    session_saved: '¡Sesión guardada!',
    sets: 'series',
    shoulders: 'Hombros',
    slam_title: 'Grand Slam Big 6',
    special: 'Especial',
    special_achievements: 'Logros Especiales',
    stitle_badges: 'Badges & Progresión',
    stitle_content_block: 'Contenido del bloque',
    stitle_gains: 'Previsión de Ganancias',
    stitle_journal: 'Diario',
    stitle_new_serie: 'Nueva Serie',
    stitle_pr: 'PR — Big 6',
    stitle_programs: 'Mis Programas',
    stitle_rpg: 'Progresión RPG',
    stitle_stats: 'Estadísticas',
    strength: 'Fuerza',
    tab_badges: 'Badges',
    tab_pr: 'PR Big 6',
    tab_rpg: 'RPG',
    tab_seances: 'Sesiones',
    tab_simu: 'Simu',
    tab_stats: 'Stats',
    theme_amber: 'ÁMBAR',
    theme_dark: 'OSCURO',
    theme_light: 'CLARO',
    tier_athlete: 'Atleta',
    tier_divine: 'Divino',
    tier_expert: 'Experto',
    tier_inactive: 'Inactivo',
    tier_initiate: 'Iniciado',
    tier_legend: 'Leyenda',
    tier_master: 'Maestro',
    tier_novice: 'Novato',
    timer_reset: 'Reset',
    timer_start: 'Iniciar',
    timer_stop: 'Parar',
    titan_title: 'Titán del Volumen',
    traps: 'Trapecios',
    triceps: 'Tríceps',
    unit_exercises: 'ejercicios',
    unit_reps: 'reps',
    unit_sessions: 'sesiones',
    unlocked_by: 'Desbloqueado por solo el {{rate}} de los atletas',
    untitled: 'Sin título',
    worker_title: 'Trabajador Incansable',
    xp_left_for: 'Faltan {{xp}} XP para el Niv. {{lvl}}',
    xp_missing: 'Faltan {{xp}} XP',

    // ── EXERCICES (CLEFS FR) ──
    'Ab wheel (roue abdominale)': 'Rueda abdominal',
    'Abduction hanche câble': 'Abducción de cadera en polea',
    'Abduction machine': 'Abducción en máquina',
    'Arnold press': 'Press Arnold',
    'Barre explosive (power clean)': 'Cargada de potencia',
    'Biceps poulie 1 bras': 'Curl de bíceps en polea a una mano',
    'Burpee avec développé': 'Burpee con press',
    'Cable crunch poulie haute': 'Crunch en polea',
    'Crossover câble': 'Cruce de poleas',
    'Crunch': 'Crunch',
    'Crunch machine': 'Crunch en máquina',
    'Curl barre EZ': 'Curl con barra EZ',
    'Curl barre droite': 'Curl con barra recta',
    'Curl câble haute poulie': 'Curl de bíceps en polea alta',
    'Curl haltères alternés': 'Curl de bíceps alterno',
    'Curl incliné haltères': 'Curl inclinado con mancuernas',
    'Curl marteau': 'Curl martillo',
    'Curl pupitre / Scott': 'Curl predicador',
    'Dips': 'Fondos',
    'Développé couché barre': 'Press de banca con barra',
    'Développé couché haltères': 'Press de banca con mancuernas',
    'Développé couché prise serrée': 'Press de banca agarre cerrado',
    'Développé décliné barre': 'Press declinado con barra',
    'Développé incliné barre': 'Press inclinado con barra',
    'Développé incliné haltères': 'Press inclinado con mancuernas',
    'Développé machine': 'Press de pecho en máquina',
    'Développé militaire barre': 'Press militar con barra',
    'Développé militaire haltères': 'Press militar con mancuernas',
    'Extensions lombaires banc romain': 'Extensiones lumbares',
    'Extensions triceps poulie haute': 'Extensiones de tríceps en polea',
    'Face pull câble': 'Face pull en polea',
    'Fentes arrière accent ischio': 'Zancadas traseras enfocadas en isquios',
    'Fentes arrière haltères': 'Zancadas traseras con mancuernas',
    'Fentes avant haltères': 'Zancadas frontales con mancuernas',
    'Fentes latérales': 'Zancadas laterales',
    'Fentes marchées': 'Zancadas caminando',
    'Gainage face (planche)': 'Plancha',
    'Gainage latéral': 'Plancha lateral',
    'Glute bridge au sol': 'Puente de glúteo',
    'Good morning barre': 'Good morning con barra',
    'Hack squat machine': 'Hack squat en máquina',
    'Hip thrust barre': 'Hip thrust con barra',
    'Hip thrust machine': 'Hip thrust en máquina',
    'Kickback fessier câble': 'Patada de glúteo en polea',
    'Kickback triceps haltère': 'Patada de tríceps',
    'Leg curl assis machine': 'Curl femoral sentado',
    'Leg curl couché machine': 'Curl femoral tumbado',
    'Leg curl debout câble': 'Curl femoral de pie en polea',
    'Leg extension machine': 'Extensión de piernas en máquina',
    'Leg press 45°': 'Prensa de piernas 45°',
    'Mollets assis machine': 'Elevación de talones sentado',
    'Mollets debout machine': 'Elevación de talones de pie',
    'Mollets haltères 1 jambe': 'Elevación de talón a una pierna',
    'Mollets presse à jambes': 'Elevación de talones en prensa',
    'Mollets à la barre': 'Elevación de talones con barra',
    'Nordic curl': 'Curl nórdico',
    'Oiseau haltères': 'Pájaros con mancuernas',
    'Pompes': 'Flexiones',
    'Pompes prise serrée': 'Flexiones diamante',
    'Presse épaule machine': 'Press de hombros en máquina',
    'Pull over haltère': 'Pullover con mancuerna',
    'Pull over poulie': 'Pullover en polea',
    'Relevé de buste banc décliné': 'Abdominales en banco declinado',
    'Relevé de jambes suspendu': 'Elevación de piernas colgado',
    'Rotation externe câble': 'Rotación externa en polea',
    'Rotation russe': 'Giro ruso',
    'Rowing barre': 'Remo con barra',
    'Rowing haltère 1 bras': 'Remo con mancuerna a una mano',
    'Rowing machine': 'Remo en máquina',
    'Rowing vertical / Upright row': 'Remo al mentón',
    'Shrugs barre': 'Encogimientos con barra',
    'Shrugs haltères': 'Encogimientos con mancuernas',
    'Shrugs machine': 'Encogimientos en máquina',
    'Sissy squat': 'Sentadilla Sissy',
    'Skull crusher barre': 'Press francés',
    'Soulevé de terre complet': 'Peso muerto completo',
    'Soulevé de terre conventionnel': 'Peso muerto convencional',
    'Soulevé de terre roumain': 'Peso muerto rumano',
    'Soulevé de terre sumo': 'Peso muerto sumo',
    'Squat avant (front squat)': 'Sentadilla frontal',
    'Squat barre': 'Sentadilla con barra',
    'Squat gobelet haltère': 'Sentadilla goblet',
    'Squat sauté': 'Sentadilla con salto',
    'Step up haltères': 'Step up con mancuernas',
    'Sumo squat haltère': 'Sentadilla sumo con mancuerna',
    'Superman': 'Superman',
    'Tirage allongé poulie basse': 'Remo en polea baja',
    'Tirage bras tendu câble': 'Jalón con brazos rectos',
    'Tirage haut kimono': 'Jalón al pecho (Kimono)',
    'Tirage poitrine poulie haute': 'Jalón al pecho',
    'Traction haute kimono isométrique': 'Sujeción isométrica Kimono',
    'Tractions neutres': 'Dominadas neutras',
    'Tractions pronation': 'Dominadas pronas',
    'Tractions supination': 'Dominadas supinas',
    'Triceps machine': 'Extensión de tríceps en máquina',
    'Triceps poulie 1 bras': 'Tríceps a una mano en polea',
    'Écarté haltères': 'Aperturas con mancuernas',
    'Écarté machine / Pec deck': 'Contractor de pecho',
    'Élévation frontale haltères': 'Elevaciones frontales con mancuernas',
    'Élévation latérale câble': 'Elevaciones laterales en polea',
    'Élévation latérale haltères': 'Elevaciones laterales con mancuernas',
  },
  ja: {
    abs: '腹筋',
    accumulated: '累計',
    achievements: 'アチーブメント',
    all: 'すべて',
    back: '背筋',
    biceps: '二頭筋',
    breaker_title: 'リミット・ブレイカー',
    btn_add_list: 'リストに追加',
    btn_back: 'プログラムに戻る',
    btn_confirm_session: 'セッションを確定 (ログ)',
    btn_export: 'エクスポート',
    btn_import: 'インポート',
    btn_new: '新規作成',
    btn_save: '保存',
    btn_save_profile: 'プロフィールを保存',
    btn_save_prog: '保存',
    calves: 'ふくらはぎ',
    cameleon_title: 'カメレオン',
    career_stats: 'キャリア統計',
    chain_core: '体幹',
    chain_full_body: '全身',
    chain_lower_ant: '下半身前面',
    chain_lower_post: '下半身背面',
    chain_upper_ant: '上半身前面',
    chain_upper_post: '上半身背面',
    choose_ex: '種目を選択',
    choose_exercise: 'エクササイズを選択',
    confirm_delete: 'このプログラムを削除しますか？',
    confirm_session: 'セッションを確定しますか？',
    deload: 'ディロード',
    endurance: '筋持久力',
    est_hybrid_1rm: '推定ハイブリッド1RM',
    exercises: 'エクササイズ',
    filter_all: 'すべて',
    filter_all_dates: '-- すべての日付 --',
    filter_all_types: '-- すべてのタイプ --',
    filter_date: '日付',
    filter_ex: '種目',
    filter_type: 'タイプ',
    fullbody: '全身',
    global_level: '総合レベル',
    glutes: '臀筋',
    hams: 'ハムストリング',
    hyperstrength: '最大筋力 (PR)',
    hypertrophy: '筋肥大',
    invalid_fields: '入力内容が正しくありません',
    label_1rm_max: '1RM MAX',
    label_add_ex: '種目を追加',
    label_age: '年齢',
    label_chart_empty: '種目を選択して進捗を表示',
    label_chart_pr: '推定1RM推移',
    label_chart_vol: 'セッションごとのボリューム',
    label_date: '日付',
    label_ex: '種目',
    label_ex_analyze: '種目分析',
    label_ex_diff: '実施種目数',
    label_gain_global: '推定総合獲得',
    label_lang: '言語',
    label_muscles: '部位別',
    label_nom: '姓',
    label_pds: '重量 (kg)',
    label_poids: '体重 (kg)',
    label_pr_done: '達成PR数',
    label_prenom: '名',
    label_prog_type: 'セッションタイプ (ログ用)',
    label_rep: 'レップ数',
    label_score_global: '総合スコア',
    label_ser: 'セット数',
    label_sessions: 'セッション数',
    label_taille: '身長 (cm)',
    label_theme: 'テーマ',
    label_timer: '休憩タイマー',
    label_type: 'セッションタイプ',
    label_vol_total: '総ボリューム',
    lang_updated_to: '言語を更新しました',
    lumbars: '腰部',
    lvl: 'レベル',
    lvl_avg: '平均レベル: ',
    lvl_keep_training: 'トレーニングを続けよう！',
    lvl_up_global: '総合レベルアップ！',
    menu_home: 'RPG (ホーム)',
    menu_profil: 'プロフィール',
    menu_settings: '設定',
    mono_title: 'モノリス',
    new_program: '新規プログラム',
    no_data: 'データなし',
    no_programs: '保存されたプログラムはありません。',
    no_sets: 'セットが見つかりません。<br>最初のセッションを入力してください！',
    no_sets_filter: 'このフィルターに該当するセットはありません。',
    p_1y: '1年間',
    p_30d: '直近30日間',
    p_7d: '直近7日間',
    p_90d: '直近90日間',
    p_all: 'すべて',
    pecs: '胸筋',
    pillar_title: 'ジムの柱',
    placeholder_prog_name: 'プログラム名...',
    pr_on: 'PR達成日',
    profile_saved: 'プロフィールを保存しました！',
    prog_by_muscle: '部位別進行状況 (RPG)',
    progress: '進行状況',
    quads: '大腿四頭筋',
    rarity_common: 'コモン',
    rarity_epic: 'エピック',
    rarity_legendary: 'レジェンダリー',
    rarity_locked: 'ロック',
    rarity_mythic: 'ミシック',
    rarity_rare: 'レア',
    rarity_relic: 'レリック',
    rarity_uncommon: 'アンコモン',
    records: '記録 (PR)',
    saved: '保存しました',
    session_saved: 'セッションを保存しました！',
    sets: 'セット',
    shoulders: '肩',
    slam_title: 'Big 6 グランドスラム',
    special: 'スペシャル',
    special_achievements: 'スペシャルアチーブメント',
    stitle_badges: 'バッジと進行状況',
    stitle_content_block: 'ブロック内容',
    stitle_gains: '獲得予想',
    stitle_journal: '履歴',
    stitle_new_serie: '新しいセット',
    stitle_pr: 'PR — Big 6',
    stitle_programs: 'マイプログラム',
    stitle_rpg: 'RPG進行状況',
    stitle_stats: '統計',
    strength: '筋力向上',
    tab_badges: 'バッジ',
    tab_pr: 'PR Big 6',
    tab_rpg: 'RPG',
    tab_seances: '記録',
    tab_simu: 'シミュレーション',
    tab_stats: '統計',
    theme_amber: 'アンバー',
    theme_dark: 'ダーク',
    theme_light: 'ライト',
    tier_athlete: 'アスリート',
    tier_divine: '神級',
    tier_expert: 'エキスパート',
    tier_inactive: '非アクティブ',
    tier_initiate: '見習い',
    tier_legend: 'レジェンド',
    tier_master: 'マスター',
    tier_novice: '初心者',
    timer_reset: 'リセット',
    timer_start: '開始',
    timer_stop: '停止',
    titan_title: 'ボリューム・タイタン',
    traps: '僧帽筋',
    triceps: '三頭筋',
    unit_exercises: '種目',
    unit_reps: 'レップ',
    unit_sessions: 'セッション',
    unlocked_by: 'アスリートのわずか {{rate}} が解除',
    untitled: '無題',
    worker_title: 'ハードワーカー',
    xp_left_for: 'レベル {{lvl}} まであと {{xp}} XP',
    xp_missing: 'あと {{xp}} XP',

    // ── EXERCICES (CLEFS FR) ──
    'Ab wheel (roue abdominale)': 'アブローラー',
    'Abduction hanche câble': 'ケーブル・アブダクション',
    'Abduction machine': 'アブダクション・マシン',
    'Arnold press': 'アーノルドプレス',
    'Barre explosive (power clean)': 'パワークリーン',
    'Biceps poulie 1 bras': 'ワンアーム・ケーブルカール',
    'Burpee avec développé': 'バーピー・プレス',
    'Cable crunch poulie haute': 'ケーブル・クランチ',
    'Crossover câble': 'ケーブル・クロスオーバー',
    'Crunch': 'クランチ',
    'Crunch machine': 'アブ・マシン',
    'Curl barre EZ': 'EZバーカール',
    'Curl barre droite': 'バーベルカール',
    'Curl câble haute poulie': 'ハイケーブル・カール',
    'Curl haltères alternés': 'ダンベルカール',
    'Curl incliné haltères': 'インクライン・ダンベルカール',
    'Curl marteau': 'ハンマーカール',
    'Curl pupitre / Scott': 'プリチャーカール',
    'Dips': 'ディップス',
    'Développé couché barre': 'バーベル・ベンチプレス',
    'Développé couché haltères': 'ダンベル・ベンチプレス',
    'Développé couché prise serrée': 'ナロー・ベンチプレス',
    'Développé décliné barre': 'デクライン・バーベル・ベンチプレス',
    'Développé incliné barre': 'インクライン・バーベル・ベンチプレス',
    'Développé incliné haltères': 'インクライン・ダンベル・ベンチプレス',
    'Développé machine': 'チェストプレス・マシン',
    'Développé militaire barre': 'バーベル・ミリタリープレス',
    'Développé militaire haltères': 'ダンベル・ミリタリープレス',
    'Extensions lombaires banc romain': 'バックエクステンション',
    'Extensions triceps poulie haute': 'トライセプス・プレスダウン',
    'Face pull câble': 'フェイスプル',
    'Fentes arrière accent ischio': 'ハムストリング狙いバックランジ',
    'Fentes arrière haltères': 'バック・ランジ',
    'Fentes avant haltères': 'フロント・ランジ',
    'Fentes latérales': 'サイドランジ',
    'Fentes marchées': 'ウォーキング・ランジ',
    'Gainage face (planche)': 'プランク',
    'Gainage latéral': 'サイドプランク',
    'Glute bridge au sol': 'グルートブリッジ',
    'Good morning barre': 'グッドモーニング',
    'Hack squat machine': 'ハックスクワット',
    'Hip thrust barre': 'ヒップスラスト',
    'Hip thrust machine': 'ヒップスラスト・マシン',
    'Kickback fessier câble': 'ケーブル・グルートキックバック',
    'Kickback triceps haltère': 'トライセプス・キックバック',
    'Leg curl assis machine': 'シーテッド・レッグカール',
    'Leg curl couché machine': 'ライイング・レッグカール',
    'Leg curl debout câble': 'スタンディング・レッグカール',
    'Leg extension machine': 'レッグエクステンション',
    'Leg press 45°': '45度レッグプレス',
    'Mollets assis machine': 'シーテッド・カーフレイズ',
    'Mollets debout machine': 'スタンディング・カーフレイズ',
    'Mollets haltères 1 jambe': 'シングルレッグ・カーフレイズ',
    'Mollets presse à jambes': 'レッグプレス・カーフレイズ',
    'Mollets à la barre': 'バーベル・カーフレイズ',
    'Nordic curl': 'ノルディックカール',
    'Oiseau haltères': 'リアレイズ',
    'Pompes': 'プッシュアップ',
    'Pompes prise serrée': 'ナロー・プッシュアップ',
    'Presse épaule machine': 'ショルダープレス・マシン',
    'Pull over haltère': 'ダンベル・プルオーバー',
    'Pull over poulie': 'ケーブル・プルオーバー',
    'Relevé de buste banc décliné': 'デクライン・シットアップ',
    'Relevé de jambes suspendu': 'ハンギング・レッグレイズ',
    'Rotation externe câble': '外部回転ケーブル',
    'Rotation russe': 'ロシアン・ツイスト',
    'Rowing barre': 'バーベルロウ',
    'Rowing haltère 1 bras': 'ワンアーム・ダンベルロウ',
    'Rowing machine': 'シーテッド・ロウイング・マシン',
    'Rowing vertical / Upright row': 'アップライトロウ',
    'Shrugs barre': 'バーベル・シュラッグ',
    'Shrugs haltères': 'ダンベル・シュラッグ',
    'Shrugs machine': 'シュラッグ・マシン',
    'Sissy squat': 'シシースクワット',
    'Skull crusher barre': 'スカルクラッシャー',
    'Soulevé de terre complet': 'フル・デッドリフト',
    'Soulevé de terre conventionnel': 'コンベンショナル・デッドリフト',
    'Soulevé de terre roumain': 'ルーマニアン・デッドリフト',
    'Soulevé de terre sumo': '相撲デッドリフト',
    'Squat avant (front squat)': 'フロントスクワット',
    'Squat barre': 'バーベルスクワット',
    'Squat gobelet haltère': 'ゴブレットスクワット',
    'Squat sauté': 'ジャンプスクワット',
    'Step up haltères': 'ステップアップ',
    'Sumo squat haltère': 'ワイド・スクワット',
    'Superman': 'スーパーマン',
    'Tirage allongé poulie basse': 'シーテッド・ケーブルロウ',
    'Tirage bras tendu câble': 'ストレートアーム・プルダウン',
    'Tirage haut kimono': 'ラットプルダウン (着物)',
    'Tirage poitrine poulie haute': 'ラットプルダウン',
    'Traction haute kimono isométrique': 'アイソメトリック・着物ホールド',
    'Tractions neutres': 'パラレル懸垂',
    'Tractions pronation': 'プルアップ',
    'Tractions supination': 'チンアップ',
    'Triceps machine': 'トライセプス・マシン',
    'Triceps poulie 1 bras': 'ワンアーム・トライセプス・プレスダウン',
    'Écarté haltères': 'ダンベル・フライ',
    'Écarté machine / Pec deck': 'ペックデック',
    'Élévation frontale haltères': 'フロントレイズ',
    'Élévation latérale câble': 'ケーブル・サイドレイズ',
    'Élévation latérale haltères': 'サイドレイズ',
  },
};
